Name = "repos"
Owner = "Niklas Heer"
Version = "0.1.0"
Description = "A tool to manage your git repos."
Framework = "mitchellh_cli"

[[Commands]]
  Name = "jump"
  FunctionName = ""
  Synopsis = "Goto the root directory of your repos."
  Help = ""

[[Commands]]
  Name = "list"
  FunctionName = ""
  Synopsis = "List all repos."
  Help = ""

[[Commands]]
  Name = "status"
  FunctionName = ""
  Synopsis = "Print the git status for each repo."
  Help = ""

[[Commands]]
  Name = "add"
  FunctionName = ""
  Synopsis = "Add a new repo." 
  Help = ""
